spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  sql:
    init:
      mode: always
      data-locations: data.sql
      #schema-locations: schema.sql
      encoding: UTF-8

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: true

logging:
  level:
    ROOT: ERROR